#!/usr/bin/env python3
"""Splices the `Rung` layout into the IDL generated by `anchor build`.

Anchor puts into the IDL only the accounts mentioned by type in `#[derive(Accounts)]`.
Rungs are created from `remaining_accounts`, because the treasurer chooses their count,
so `Rung` does not make it into the IDL — and without it the SDK has nothing to decode a rung with.

The fragment is produced by `programs/treasury-runway/tests/idl_rung.rs` with the same
`IdlBuild` Anchor uses for the rest of the IDL: the source of the layout stays single, and
it is in Rust. Here there is only the splicing.

This dies in M2: `redeem_rung` and its neighbours take `Account<'info, Rung>`, and Anchor
will put the type in itself. Then this file, the step in `program-wsl.sh` and the test
generator are deleted together.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
IDL = ROOT / "target" / "idl" / "treasury_runway.json"
FRAGMENT = ROOT / "target" / "idl" / "rung-fragment.json"


def short(name: str) -> str:
    """`IdlBuild` returns the full module path, while the IDL from anchor-cli uses the short name.

    A mismatch here would not fail at build time: the client simply would not find the type a
    field refers to, and it would look like a broken decoder.
    """
    return name.rsplit("::", 1)[-1]


def normalize(node):
    """Shortens type names everywhere they occur — both in definitions and in
    `{"defined": {"name": ...}}` references."""
    if isinstance(node, dict):
        return {
            key: short(value) if key == "name" and isinstance(value, str) else normalize(value)
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [normalize(item) for item in node]
    return node


def main() -> int:
    if not FRAGMENT.exists():
        print(f"no {FRAGMENT}: the idl_rung test must run first", file=sys.stderr)
        return 1

    idl = json.loads(IDL.read_text(encoding="utf-8"))
    fragment = normalize(json.loads(FRAGMENT.read_text(encoding="utf-8")))

    for section in ("accounts", "types"):
        existing = {item["name"] for item in idl.get(section, [])}
        added = [item for item in fragment[section] if item["name"] not in existing]
        # If the type is already there — Anchor has learned to see it itself, and the splice is
        # no longer needed. Silently overwriting it with our copy is not an option: they can
        # only drift in one direction, and not in our favour.
        idl[section] = sorted(idl.get(section, []) + added, key=lambda item: item["name"])

    IDL.write_text(json.dumps(idl, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
